name: Sonar Code Quality Check

on:
  push:
    branches: [ main ]

jobs:
  sonar-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulated Sonar Scan
        run: |
          echo "Running Sonar analysis..."
          echo "No critical issues found"
          echo "Quality Gate: PASSED"
